name: Ubuntu Latest
on: push

jobs:
  buildOnUbuntu:
    runs-on: ubuntu-24.04

    steps:
    - name: checkout sources
      uses: actions/checkout@v4

    - name: Install Dependencies
      shell: bash
      run: |
        apt-get update && apt-get install -y sudo p7zip-full wget file libwayland-cursor0 libwayland-egl1
        sudo ln -fs /usr/share/zoneinfo/UTC /etc/localtime
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends software-properties-common
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8'
        arch: 'linux_gcc_64'
        extra: '--external 7z'
        modules: 'qtimageformats qtwaylandcompositor'
        aqtversion: "==3.1.*"

    - name: Build Laigter
      shell: bash
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        qmake CONFIG+=release PREFIX=/usr
        make -j$(nproc)
        make INSTALL_ROOT=appdir install
        
    - name: Create Appimage
      run: |
        export ICON="dist/laigter.png"
        export DESKTOP="dist/laigter.desktop"
        export OUTNAME="Laigter-x86_64.AppImage"
        
        curl -Lo quick-sharun https://raw.githubusercontent.com/pkgforge-dev/Anylinux-AppImages/main/useful-tools/quick-sharun.sh
        chmod +x quick-sharun
        
        ./quick-sharun appdir/usr/local/bin/laigter --make-appimage --output "$OUTNAME" --icon "$ICON" --desktop "$DESKTOP"

# Or if it has a simpler mode (some versions support one-liner bundling):
# ./quick-sharun /path/to/your/laigter-binary --make-appimage

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifact
        path: Laigter-x86_64.AppImage 

    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: Laigter-x86_64.AppImage
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

